config/routes.rb
Rails.application.routes.draw do
  get '/users/dashboard' => 'users#dashboard', as: :user_root # creates user_root_path
  get '/users/my_properties' => 'users#my_properties'
  get '/users/magnate' => 'users#magnate'

  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users do
    resources :messages
  end

  resources :properties
  resources :home, only: :index

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!

    def index

    end

    def show
        @message = Message.find(params[:id])
        @property = Property.find(@message.property_id)
    end

    def new
        @message = Message.new
    end

    def create
        @message = Message.create!(message_params)
        redirect_to property_path(@message.property_id)
    end

    private

    def message_params
        params.require(:message).permit(:sender_id, :recipient_id, :message_content, :application, :property_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<h2>Inbox Messages</h2>

<% current_user.received_messages.each do |m| %>
    <%= link_to User.find(m.sender_id).email, "/users/#{m.sender_id}/messages/#{m.id}" %>
    <br />
<% end %>

<br /><br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>

app/views/messages/new.html.erb
<h2>Compose a New Message</h2>
<br />
<%= form_for(@message, url: user_messages_path) do |f| %>
  <%= render "devise/shared/error_messages", resource: @message %>

  <div class="field">
    <%= f.hidden_field :sender_id, value: params[:user_id] %>
    <%= f.hidden_field :recipient_id, value: params[:recipient_id] %>
    <%= f.hidden_field :application, value: params[:application] %>
    <%= f.hidden_field :property_id, value: params[:property_id] %>
  </div>

  <div class="field">
    <%= f.label :message_content %><br />
    <%= f.text_area :message_content %>
  </div>

  <div class="actions">
    <%= f.submit "Send Message" %>
  </div>
<% end %>
<br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>

app/views/messages/show.html.erb
<h2>Your Message</h2>
<hr>
<h4>From: <%= User.find(@message.sender_id).email %></h4>
<p><%= @message.message_content %></p>
<% if @message.application %>
    <!--<%= link_to "Approve Application", property_path(@message.property_id, property: {tenant_id: 12 }), method: "put" %>-->
    <%= form_for(@property, url: property_path(@property)) do |f| %>
        <%= render "devise/shared/error_messages", resource: @property %>

        <div class="field">
            <%= f.hidden_field :tenant_id, value: @message.sender_id %>
            <%= f.hidden_field :available, value: false %>
        </div>

        <div class="actions">
            <%= f.submit "Approve Application" %>
        </div>
    <% end %>
<% end %>
<br />

<%= link_to "Reply", { 
    controller: "messages", 
    action: "new", 
    user_id: current_user.id, 
    recipient_id: @message.sender_id, 
    property_id: @property.id, 
    application: false 
}, method: "get"%>

<hr>
<br />
<%= button_to "Return to Inbox", user_messages_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>