config/routes.rb
Rails.application.routes.draw do
  get '/users/dashboard' => 'users#dashboard', as: :user_root # creates user_root_path
  get '/users/my_properties' => 'users#my_properties'
  get '/users/magnate' => 'users#magnate'

  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users do
    resources :messages
  end

  resources :properties
  resources :home, only: :index

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :landlord, class_name: "User"
  belongs_to :tenant, class_name: "User", optional: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_property, only: [:show, :edit, :update, :destroy]
    
    def index

    end

    def show

    end


    def new
        @property = Property.new
    end

    def create
        @property = Property.new(property_params)
        @property.landlord_id = current_user.id
        @property.save!
        redirect_to property_path(@property)
    end


    def edit

    end

    def update
        @property.update(property_params)
        redirect_to property_path(@property)
    end


    def destroy
        @property.destroy
        redirect_to "/users/my_properties"
    end

    private

    def property_params
        params.require(:property).permit(:landlord_id, :address, :rooms, :bathrooms, :squarefeet, :storeys, :rent, :description, :available, :tenant_id)
    end

    def find_property
        @property = Property.find(params[:id])
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_property_form.html.erb
<%= form_for(@property) do |f| %>
  <%= render "devise/shared/error_messages", resource: @property %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
  </div>

  <div class="field">
    <%= f.label :rooms %><br />
    <%= f.number_field :rooms %>
  </div>

  <div class="field">
    <%= f.label :bathrooms %><br />
    <%= f.number_field :bathrooms %>
  </div>

  <div class="field">
    <%= f.label :squarefeet %><br />
    <%= f.number_field :squarefeet %>
  </div>

  <div class="field">
    <%= f.label :storeys %><br />
    <%= f.number_field :storeys %>
  </div>

  <div class="field">
    <%= f.label :rent %><br />
    <%= f.number_field :rent %>
  </div>

  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h2>Property Edit</h2>
<br>
<%= render "property_form" %>
<br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>

app/views/properties/index.html.erb
<h2>Available Properties</h2>

<% Property.all.each do |p| %>
    <% if p.available == true %>
        <%= link_to p.address, property_path(p.id) %>
        <br>
        Rooms: <%= p.rooms %> , Bathrooms: <%= p.bathrooms %>
        <br>
        Size: <%= p.squarefeet %>sqft, Rent: <%= p.rent %>
        <br><hr>
    <% end %>
<% end %>
<br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>

app/views/properties/new.html.erb
<h2>List a New Property</h2>
<br>
<%= render "property_form" %>
<br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>

app/views/properties/show.html.erb
<h2>Property Listing</h2>
<br>
Address: <%= @property.address %><br>
Bedrooms: <%= @property.rooms %><br>
Bathrooms: <%= @property.bathrooms %><br>
Squarefootage: <%= @property.squarefeet %><br>
Rent: <%= @property.rent %><br>
Currently Available: <%= @property.available %><br>
Description: <%= @property.description %><br><br>
<!-- Add conditionally shown buttons to edit the property
if the user viewing the property is also the owner. -->
<% if current_user.id == @property.landlord_id %>
    <%= button_to "Edit", edit_property_path(@property), method: "get" %>
    <%= button_to "Delete", property_path(@property), method: "delete" %>
<% else %>
    <%= link_to "Message Owner", { controller: "messages", action: "new", user_id: current_user.id, recipient_id: @property.landlord_id, property_id: @property.id, application: false }, method: "get"%><br />
    <%= link_to "Start Application", { controller: "messages", action: "new", user_id: current_user.id, recipient_id: @property.landlord_id, property_id: @property.id, application: true }, method: "get"%>
<% end %>
<br /><br />
<%= button_to "Return to Dashboard", user_root_path, method: "get" %>
<%= button_to "Logout", destroy_user_session_path, method: "delete" %>